---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, prompt = TRUE)
options(prompt = "R> ")

# Load external .R file
# knitr::read_chunk("01-prelim.R")
# knitr::read_chunk("05-iris.R")
# knitr::read_chunk("07-cardiac.R")
# knitr::read_chunk("08-smoking.R")
```

<!-- ```{r prelim, include = FALSE} -->
<!-- ``` -->

## Abstract

TBC.

*Keywords*: to, be, confirmed

## Links

- Presentation slides - [PDF](http://phd3.haziqj.ml/phd-presentation-3-handout.pdf)
- Source code - [GitHub](https://github.com/haziqj/soc-stat-meet-bgtvi)

## Supplementary material

## References

***

Copyright (C) 2018 [Haziq Jamil](http://haziqj.ml). 

```{r move, include = FALSE}
file.copy("README.md", "../README.md", overwrite = TRUE)
files <- list.files("README_files/figure-markdown_github")
if (!dir.exists("../README_files/figure-markdown_github")) {
  dir.create("../README_files/")
  dir.create("../README_files/figure-markdown_github")
}
file.copy("README_files/", "../", recursive = TRUE)
```
